version: 1.0.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: Environment
  name: nuget.org
notifications:
- provider: Email
  to:
  - oliver@oliversturm.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
